apiVersion: v1
kind: Service
metadata:
  name: cloud-native-application-service
spec:
  type: NodePort
  selector:
    app:  cloud-native-application
  ports:
    - targetPort: 8080
      port: 8080
      nodePort: 30000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  cloud-native-application-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cloud-native-application
  template:
    metadata:
      labels:
        app: cloud-native-application
    spec:
      containers:
        - name:  cloud-native-application
          image: danielcifuentes54/cloud-native-application
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080