on:
  workflow_dispatch:
  push:
name: cloud native application
jobs:
  deploy:
    name: CI and CD
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify
      - name: build and push to docker
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ github.repository }}
          tags: ${{ github.run_id }}
      - name: Deploy to Kubernetes
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USERNAME }}
          key: ${{ secrets.AWS_KEY }}
          script: kubectl set image deployment/cloud-native-application-deployment cloud-native-application=danielcifuentes54/cloud-native-application:${{ secrets.AWS_KEY }}
